# Generated by Django 4.0.6 on 2022-07-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_project_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='writer',
        ),
    ]
