# Generated by Django 4.0.6 on 2022-07-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0005_article_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
